Projekt Mappe/Website/Gui/Controllers/AuthController.cs
using Gui.Helpers;
using Gui.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Gui.Controllers
{
    public class AuthController : Controller
    {
        // GET: AuthController
        public ActionResult Index()
        {

            return View();
        }

        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(LoginViewModel lvm)
        {
            ServicePointManager.ServerCertificateValidationCallback = (obj, certificate, chain, errors) => true;
            ServiceHelper.GetServiceClientWithCredentials(lvm.Username, lvm.Password);
            bool canLogIn = false;
            using (var authsvc = ServiceHelper.GetAuthServiceClient())
            {
                canLogIn = authsvc.Login(lvm.Username, lvm.Password);
            }

            if (!canLogIn)
            {
                ViewBag.StatusMessage = "Could not login with the given credentials";
                return View();
            }
            else
            {
                AuthHelper.Login(lvm);
                return RedirectToAction("Index", "User", new { userName = lvm.Username });
            }
        }

        public ActionResult Logout()
        {
            AuthHelper.Logout();
            return RedirectToAction("Index", "Home");
        }
        public ActionResult MembersOnly()
        {
            return View();
        }
    }
}

Projekt Mappe/Website/Gui/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Gui.OrderServiceRef;
using Gui.OrderLineServiceRef;
using Gui.WalletServiceRef;
using Gui.UserServiceRef;
using Gui.CustomerServiceRef;
using Gui.StorageServiceRef;
using System.Dynamic;
using Gui.Helpers;

namespace Gui.Controllers
{
    public class OrderController : Controller
    {
        OrderServiceClient client = new OrderServiceClient();
        OrderLineServiceClient olClient = new OrderLineServiceClient();
        WalletServiceClient walletClient = new WalletServiceClient();
        StorageServiceClient storageClient = new StorageServiceClient();

        // GET: Order
        public ActionResult Index()
        {
            return View(client.GetAllOrders());
        }

        // GET: Order/Details/5
        public ActionResult Details(int id)
        {
            return View(doBCVM(id));
        }

        // GET: Order/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Order/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Order/Edit/5
        public ActionResult Edit(int id)
        {
            return View(olClient.GetOrderLine(id));
        }

        [HttpPost]
        public ActionResult EditAmount(int id, int orderID, string text)
        {
            olClient.EditOrderLinePrice(id, orderID, text);
            return RedirectToAction("Details", new { id = orderID });
        }

        // POST: Order/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, OrderLineServiceRef.OrderLine orderline, string text)
        {
            try
            {
                int amount = orderline.Amount + Convert.ToInt32(text);
                orderline = olClient.GetOrderLine(id);
                orderline.TotalPrice = amount * orderline.Drink.Price;
                orderline.Amount = amount;
                olClient.EditOrderLine(orderline);


                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        // GET: Order/Delete/5
        public ActionResult DeleteOrder(int ID)
        {
            client.DeleteOrderByID(ID);
            return RedirectToAction("Index", "User", new { userName = AuthHelper.CurrentUser.Username });
        }

        // POST: Order/Delete/5
        [HttpPost]
        public ActionResult DeleteOrder(int ID, FormCollection collection)
        {
            try
            {
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Order/Delete/5
        public ActionResult Delete(string type, int orderlineID, int id)
        {
            olClient.DeleteOrderLineByID(type, orderlineID, id);
            return View("Details", doBCVM(id));
        }

        [HttpPost]
        public ActionResult Delete(int OrderLineId, FormCollection collection)
        {
            try
            {
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public dynamic doBCVM(int id)
        {
            dynamic BCVM = new ExpandoObject();
            BCVM.Order = client.GetOrder(id);
            BCVM.OrderLines = client.GetOrder(id).OrderLines;
            return BCVM;
        }

        public ActionResult CompleteOrder(int id)
        {
            Order order = client.GetOrder(id);

            if (storageClient.CompleteOrder(order.ID) == true)
            {
                //storageClient.CompleteOrder(order.ID);
                order.Status = "Complete";
                decimal hej = walletClient.getWalletByUsername(AuthHelper.CurrentUser.Username).Balance - order.TotalPrice;
                walletClient.UpdateBalanceByUserId(hej, client.GetUser(AuthHelper.CurrentUser.Username).ID);
                client.CompleteOrder(order);

                return View("OrderSucces");
            }
            else
            {
                client.DeleteOrderByID(order.ID);
                return View("OrderFailed");
            }

            
        }

        public ActionResult CreateOrder(int cusID)
        {
            DateTime date = DateTime.Now;

            Order order = new Order
            {
                TotalPrice = 0,
                Discount = 0,
                Date = date,
                Status = "Incomplete",
                User = client.GetUser(AuthHelper.CurrentUser.Username),
                Customer = client.GetCustomer(cusID)
            };

            client.CreateOrder(order);
            return RedirectToAction("Index");
        }
    }
}

Projekt Mappe/Website/Gui/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Gui.UserServiceRef;
using Gui.FavoritServiceRef;
using Gui.Models;
using System.Text.RegularExpressions;

namespace Gui.Controllers
{
    public class RegisterController : Controller
    {
        UserServiceClient client = new UserServiceClient();
        FavoritesServiceClient faClient = new FavoritesServiceClient();

        // GET: Register
        public ActionResult Index()
        {
            return View();
        }
        //[HttpPost]
        //public ActionResult Index()
        //{
        //    return View();
        //}

        public ActionResult AutomaticRedirect()
        {
            return RedirectToAction("Index", "Home");
        }


        // GET: Register/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Register/Create

        [HttpPost]
        public ActionResult Create(Gui.UserServiceRef.User user)
        {
            if (string.IsNullOrEmpty(user.Password))
            {
                ModelState.AddModelError("Password", "Du har ikke indtastet et Password");
            }
            if (string.IsNullOrEmpty(user.LastName))
            {
                ModelState.AddModelError("LastName", "Du har ikke indtastet dit Lastname");
            }
            if (string.IsNullOrEmpty(user.FirstName))
            {
                ModelState.AddModelError("FirstName", "Du har ikke indtastet dit Firstname");
            }
            if (string.IsNullOrEmpty(user.Gender))
            {
                ModelState.AddModelError("Gender", "Du har ikke valgt et køn");
            }
            if (string.IsNullOrEmpty(user.UserName))
            {
                ModelState.AddModelError("UserName", "Du har ikke indtastet et Username");
            }
            if (!string.IsNullOrEmpty(user.Email))
            {
                string emailRegex = @"^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$";
                Regex re = new Regex(emailRegex);
                if (!re.IsMatch(user.Email))
                {
                    ModelState.AddModelError("Email", "Indtast venligst korrekt Email");
                }
            }
            else
            {
                ModelState.AddModelError("Email", "Du har ikke indtastet din Email");
            }
            if (!string.IsNullOrEmpty(user.Phone))
            {
                string phoneRegex = "^([0-9]{8})$";
                Regex pe = new Regex(phoneRegex);
                if (!pe.IsMatch(user.Phone))
                {
                    ModelState.AddModelError("Phone", "Indtast venligst korrekt Telefon nr");
                }
            }
            else
            {
                ModelState.AddModelError("Phone", "Du har ikke indtastet Telefon nr");
            }
            if (ModelState.IsValid)
            {

                client.CreateUser(user);
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

Projekt Mappe/Website/Gui/Views/Shared/_Layout.cshtml
@using Gui.Helpers;
@using Gui.OrderServiceRef;
@using Gui.CustomerServiceRef;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")   

    @{
        OrderServiceClient oClient = new OrderServiceClient();
        CustomerServiceClient cClient = new CustomerServiceClient();
    }
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <img class="movebanner" src="~/Pictures/drinkzy.png" heigh="50px" width="200px" />
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
              @Html.ActionLink(" ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Find Bar", "FindBar", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li style="margin-top:12px;">
                        @using (Html.BeginForm("Search", "Search", FormMethod.Post))
                        {
                            <input type="text" name="text" value="" />
                            <input type="submit" id="sumbitText" value="Søg" />
                        }
                    </li>
                    <li>@(AuthHelper.IsLoggedIn() ? @Html.ActionLink("Profile: " + AuthHelper.CurrentUser.Username, "Index", "User") : @Html.ActionLink("Log ind", "Login", "Auth"))  </li>
                    <li>@if(!AuthHelper.IsLoggedIn()){@Html.ActionLink("Opret Bruger", "Create", "Register")}</li>
                    <li>@if (AuthHelper.IsLoggedIn())
                    {
                        <a href="@Url.Action("Details", "Order", new { id = oClient.getLastOrderIDByUser(AuthHelper.CurrentUser.Username)})">@oClient.getAmountOfItemsInOrder(AuthHelper.CurrentUser.Username)<img src="https://upload.wikimedia.org/wikipedia/commons/8/8d/Carrito.png" alt="" height="20px" width="auto" /></a>
                    }</li>
                    <li>@if (AuthHelper.IsLoggedIn()){@Html.ActionLink("Log ud", "Logout", "Auth")}</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Drinkzy incorperated, Owned by Group 5</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>