Projekt Mappe/Website/Gui/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Gui.CustomerServiceRef;
using Gui.MenucardServiceRef;

namespace Gui.Controllers
{
    public class CustomerController : Controller
    {
        private CustomerServiceClient client = new CustomerServiceClient();
        MenuCardServiceClient menuClient = new MenuCardServiceClient();

        // GET: Customer
        public ActionResult Index()
        {
            return View();
        }

        // GET: Customer/Details/5
        public ActionResult Details(int id)
        {
            return View(menuClient.GetMenuByCustomerID(id));
        }

        public ActionResult AlchoholDetails(int id)
        {
            return View(menuClient.GetMenuByCustomerID(id));
        }

        [HttpPost]
        public ActionResult Details(MenuCard menu)
        {
            return View(menu);
        }

        // GET: Customer/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customer/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Customer/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Customer/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Customer/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Customer/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public IEnumerable<Gui.CustomerServiceRef.Customer> SearchCustomers(string search)
        {
            return client.SearchCustomer(search);
        }

        public ActionResult SearchMenucard(string text, int id)
        {
            MenuCard menu = menuClient.GetMenuByCustomerID(id);
            menu.Drinks = menuClient.getDrinksBySearchOnMenucard(text, id);
            return View(menu);
        }
    }
}

Projekt Mappe/Website/Gui/Controllers/DrinkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Gui.DrinkServiceRef;
using Gui.OrderLineServiceRef;
using Gui.OrderServiceRef;
using Gui.WalletServiceRef;
using Gui.FavoritServiceRef;
using Gui.UserServiceRef;
using System.Dynamic;
using Gui.StorageServiceRef;

namespace Gui.Controllers
{
    public class DrinkController : Controller
    {
        private UserServiceClient uClient = new UserServiceClient();
        private DrinkServiceClient client = new DrinkServiceClient();
        private OrderLineServiceClient lc = new OrderLineServiceClient();
        private OrderServiceClient orderClient = new OrderServiceClient();
        private OrderController oCtr = new OrderController();
        private WalletServiceClient walletClient = new WalletServiceClient();
        private StorageServiceClient sClient = new StorageServiceClient();
        

        // GET: Drink
        public ActionResult Index()
        {
            return View(client.getAllDrinks());
        }

        public ActionResult AlchoholIndex()
        {
            return View(client.GetAllAlchohols());
        }

        // GET: Drink/Details/5
        public ActionResult Details(int drinkId)
        {

            return View(client.GetDrink(drinkId));
        }

        public ActionResult AlchoholDetails(int drinkId)
        {
            return View(client.GetAlchohol(drinkId));
        }

        public ActionResult HelflaskDetails(int drinkId)
        {
            return View(client.GetHelflask(drinkId));
        }

        // GET: Drink/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Drink/Create
        [HttpPost]
        public ActionResult Create(int amount, int drinkId, int cusID, string UserName)
        {
            Gui.OrderLineServiceRef.OrderLine orderline = new Gui.OrderLineServiceRef.OrderLine();
            orderline.Amount = amount;

            if (sClient.getStorageByDrinkAndStorage(drinkId, cusID).Amount >= amount)
            {
                if (orderClient.GetOrderByStatus("Incomplete") != null && orderClient.GetUser(UserName).ID == orderClient.GetOrderByStatus("Incomplete").User.ID)
                {
                    if (orderClient.GetOrderByStatus("Incomplete").Customer.ID == cusID)
                    {
                        orderline.Drink = lc.GetDrink(drinkId);
                        orderline.TotalPrice = orderline.Drink.Price * orderline.Amount;
                        lc.CreateOrderLine(orderline, orderClient.GetOrderByStatus("Incomplete").ID);


                        decimal hej = orderline.Drink.Price * orderline.Amount;
                        hej = orderClient.GetOrderByStatus("Incomplete").TotalPrice + hej;
                        orderClient.UpdatePrice(orderClient.GetOrderByStatus("Incomplete"), hej);
                        return RedirectToAction("Details", "Customer", new { id = cusID });
                    }
                    else if (orderClient.GetOrderByStatus("Incomplete").Customer.ID != cusID)
                    {
                        orderClient.DeleteOrderByID(orderClient.GetOrderByStatus("Incomplete").ID);
                        oCtr.CreateOrder(cusID);
                        return Create(amount, drinkId, cusID, UserName);
                    }
                }
                else
                {
                    oCtr.CreateOrder(cusID);
                    return Create(amount, drinkId, cusID, UserName);
                }
            }
            return RedirectToAction("Details", "Customer", new { id = cusID });
        }
        public ActionResult CreateHelflask()
        {
            return View();
        }

        // POST: Drink/Create
        [HttpPost]
        public ActionResult CreateHelflask(int amount, int drinkId, int cusID, string UserName)
        {
            Gui.OrderLineServiceRef.OrderLine orderline = new Gui.OrderLineServiceRef.OrderLine();
            orderline.Amount = amount;

            if (sClient.getHelflaskStorageByHelflaskAndStorage(drinkId, cusID).Amount >= amount)
            {
                if (orderClient.GetOrderByStatus("Incomplete") != null && orderClient.GetUser(UserName).ID == orderClient.GetOrderByStatus("Incomplete").User.ID)
                {
                    if (orderClient.GetOrderByStatus("Incomplete").Customer.ID == cusID)
                    {
                        orderline.Drink = lc.GetHelflask(drinkId);
                        orderline.TotalPrice = orderline.Drink.Price * orderline.Amount;
                        lc.CreateOrderLineHelflask(orderline, orderClient.GetOrderByStatus("Incomplete").ID);


                        decimal hej = orderline.Drink.Price * orderline.Amount;
                        hej = orderClient.GetOrderByStatus("Incomplete").TotalPrice + hej;
                        orderClient.UpdatePrice(orderClient.GetOrderByStatus("Incomplete"), hej);
                        return RedirectToAction("Details", "Customer", new { id = cusID });
                    }
                    else if (orderClient.GetOrderByStatus("Incomplete").Customer.ID != cusID)
                    {
                        orderClient.DeleteOrderByID(orderClient.GetOrderByStatus("Incomplete").ID);
                        oCtr.CreateOrder(cusID);
                        return CreateHelflask(amount, drinkId, cusID, UserName);
                    }
                }
                else
                {
                    oCtr.CreateOrder(cusID);
                    return CreateHelflask(amount, drinkId, cusID, UserName);
                }

            }

            return RedirectToAction("Details", "Customer", new { id = cusID });
        }

        public ActionResult CreateAlchohol()
        {
            return View();
        }

        // POST: Drink/Create
        [HttpPost]
        public ActionResult CreateAlchohol(int amount, int drinkId, int cusID, string UserName)
        {
            Gui.OrderLineServiceRef.OrderLine orderline = new Gui.OrderLineServiceRef.OrderLine();
            orderline.Amount = amount;

            if (sClient.getAlchoholStorageByDrinkAndStorage(drinkId, cusID).Amount >= amount)
            {
                if (orderClient.GetOrderByStatus("Incomplete") != null && orderClient.GetUser(UserName).ID == orderClient.GetOrderByStatus("Incomplete").User.ID)
                {
                    if (orderClient.GetOrderByStatus("Incomplete").Customer.ID == cusID)
                    {
                        orderline.Drink = lc.GetAlchohol(drinkId);
                        orderline.TotalPrice = orderline.Drink.Price * orderline.Amount;
                        lc.CreateOrderLineAlchohol(orderline, orderClient.GetOrderByStatus("Incomplete").ID);


                        decimal hej = orderline.Drink.Price * orderline.Amount;
                        hej = orderClient.GetOrderByStatus("Incomplete").TotalPrice + hej;
                        orderClient.UpdatePrice(orderClient.GetOrderByStatus("Incomplete"), hej);
                        return RedirectToAction("Details", "Customer", new { id = cusID });
                    }
                    else if (orderClient.GetOrderByStatus("Incomplete").Customer.ID != cusID)
                    {
                        orderClient.DeleteOrderByID(orderClient.GetOrderByStatus("Incomplete").ID);
                        oCtr.CreateOrder(cusID);
                        return CreateAlchohol(amount, drinkId, cusID, UserName);
                    }
                }
                else
                {
                    oCtr.CreateOrder(cusID);
                    return CreateAlchohol(amount, drinkId, cusID, UserName);
                }
            }
            return RedirectToAction("Details", "Customer", new { id = cusID });
        }


        // GET: Drink/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Drink/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Drink/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Drink/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public dynamic doBCVM(int id)
        {
            dynamic BCVM = new ExpandoObject();
            BCVM.Drink = client.GetDrink(id);
            BCVM.Ingredients = client.GetDrink(id).Ingredients;
            return BCVM;
        }

        public IEnumerable<Gui.DrinkServiceRef.Drink> search(string text)
        {
            return client.SearchDrinks(text);
        }

        public ActionResult AddFavorit(int drinkID, string userName)
        {
            FavoritesServiceClient fClient = new FavoritesServiceClient();
            int newID = uClient.GetUserByUserName(userName).ID;
            fClient.addDrink(newID, drinkID);
            return RedirectToAction("Details", new { drinkId = drinkID });
        }

        public ActionResult AddAlchohol(int drinkID, string userName)
        {
            FavoritesServiceClient fClient = new FavoritesServiceClient();
            fClient.AddAlchohol(uClient.GetUserByUserName(userName).ID, drinkID);
            return RedirectToAction("AlchoholDetails", new { drinkId = drinkID });
        }

        public ActionResult AddHelflask(int drinkID, string userName)
        {

Projekt Mappe/Website/Gui/Views/Customer/AlchoholDetails.cshtml
@model Gui.MenucardServiceRef.MenuCard

<h2>@Model.Customer.CusName</h2>

<div style="color:white;">
    <h4>Menu</h4>
    <hr />
    @using (Html.BeginForm("SearchMenucard", "Customer", FormMethod.Post))
    {
        <input type="text" name="text" value="" />
        <input type="hidden" name="id" value="@Model.Customer.ID" />
        <input type="submit" id="sumbitText" value="Søg" />
    }
    <dl class="dl-horizontal">
        @foreach (Gui.MenucardServiceRef.Alchohol a in Model.alchohols)
        {
            <dt>

            </dt>
            <dd>
                <img src="@Url.Content(a.Img)" alt="" height="200px" width="auto" />
            </dd>
            <dt>
                Name
            </dt>
            <dd>
                @a.Name
            </dd>
            <dt>
                Procent
            </dt>
            <dd>
                @a.Procent
            </dd>
            <dt>

            </dt>
            <dd>
                <input id="Button1" type="submit" value="Tilføj til kurven" onclick="location.href='@Url.Action("Create", "Drink", new { alcId = a.ID, cusID = Model.Customer.ID })'" />
            </dd>
        }
    </dl>
</div>
<p>
    @Html.ActionLink("Tilbage til listen", "Index")
</p>

Projekt Mappe/Website/Gui/Views/Customer/Details.cshtml
@model Gui.MenucardServiceRef.MenuCard
    @using Gui.Helpers
    @using Gui.StorageServiceRef;


@{
    ViewBag.Title = "Index";
    StorageServiceClient sClient = new StorageServiceClient();
}

<h2>@Model.Customer.CusName</h2>

<div style="color:white;">
    <h4>MenuKort</h4>
    <hr />
    @using (Html.BeginForm("SearchMenucard", "Customer", FormMethod.Post))
    {
        <input type="text" name="text" value="" />
        <input type="hidden" name="id" value="@Model.Customer.ID"/>
        <input type="submit" id="sumbitText" value="Søg" />
    }
    <dl class="dl-horizontal">

        <h2>Drinks</h2>
        <table style="margin-left:50px;">
            @foreach (Gui.MenucardServiceRef.Drink d in Model.Drinks)
            {
            <tr>
                <th>
                    <h3>@d.Name</h3>
                </th>
            </tr>
            <tr>
                <th width="270px" rowspan="3">
                    <a href="@Url.Action("Details", "Drink", new { drinkId = d.ID })"><img src="@Url.Content(d.Img)" alt="" height="200px" width="auto" /></a>
                </th>
                <td valign="top">
                    @d.Description
                </td>
            </tr>
            <tr>
                <td valign="top">
                    Pris: @d.Price dkk. <br />
                    Antal tilbage; @sClient.getStorageByDrinkAndStorage(d.ID, Model.Customer.ID).Amount;
                </td>
            </tr>
            <tr>
                <td valign="bottom">
                    @if (AuthHelper.IsLoggedIn())
                    {
                        if (sClient.getStorageByDrinkAndStorage(d.ID, Model.Customer.ID) == null ||
                            sClient.getStorageByDrinkAndStorage(d.ID, Model.Customer.ID).Amount <= 0)
                        {
                            <p>UDSOLGT!</p>
                        }
                        else
                        {
                            using (Html.BeginForm("Create", "Drink", FormMethod.Post))
                            {
                                    <input type="hidden" name="drinkId" value="@d.ID" />
                                    <input type="hidden" name="cusID" value="@Model.Customer.ID" />
                                    <input type="text" name="amount" value="" style="width:30px;" />
                                    <input type="hidden" name="UserName" value="@AuthHelper.CurrentUser.Username" />
                                    <input type="submit" id="sumbitText" value="Tilføj" /> 
                                    <input id="btnDetails" type="button" value="Detaljer" onclick="location.href='@Url.Action("Details", "Drink", new { drinkId = d.ID })'" />
                            }
                        }
                    }
                    else
                    {
                        <p>Du skal være logget ind før du kan købe</p>
                        <input id = "btnDetails" type = "button" value = "Detaljer" onclick = "location.href='@Url.Action("Details", "Drink", new { drinkId = d.ID })'" />
                    }

                </td>
            </tr>
            }
        </table>
        <hr />

        <h2>Alkohol</h2>
        <table style="margin-left: 50px;">
            @foreach (Gui.MenucardServiceRef.Alchohol d in Model.alchohols)
            {
            <tr>
                <th>
                    <h3>@d.Name</h3>
                </th>
            </tr>
            <tr>
                <th width="270px" rowspan="3">
                    <a href="@Url.Action("AlchoholDetails", "Drink", new { drinkId = d.ID })"><img src="@Url.Content(d.Img)" alt="" height="200px" width="auto" /></a>
                </th>
                <td valign="top">
                    Procent: @d.Procent
                </td>
            </tr>
            <tr>
                <td valign="top">
                    Pris: @d.Price dkk. <br />
                    Antal tilbage; @sClient.getAlchoholStorageByDrinkAndStorage(d.ID, Model.Customer.ID).Amount;
                </td>
            </tr>
            <tr>
                <td valign="bottom">
                    @if (AuthHelper.IsLoggedIn())
                    {
                        if (sClient.getAlchoholStorageByDrinkAndStorage(d.ID, Model.Customer.ID) == null ||
                            sClient.getAlchoholStorageByDrinkAndStorage(d.ID, Model.Customer.ID).Amount <= 0)
                        {
                            <p>UDSOLGT!</p>
                        }
                        else
                        {
                            using (Html.BeginForm("CreateAlchohol", "Drink", FormMethod.Post))
                            {
                                // int amount, int drinkId, int cusID, string UserName;
                                <input type="hidden" name="drinkId" value="@d.ID" />
                                    <input type="hidden" name="cusID" value="@Model.Customer.ID" />
                                    <input type="text" name="amount" value="" style="width:30px;" />
                                    <input type="hidden" name="UserName" value="@AuthHelper.CurrentUser.Username" />
                                    <input type="submit" id="sumbitText" value="Tilføj" />
                                    <input id="btnDetails" type="button" value="Detaljer" onclick="location.href='@Url.Action("AlchoholDetails", "Drink", new { drinkId = d.ID })'" />
                            }
                        }
                    }
                    else
                    {
                        <p>Du skal være logget ind før du kan købe</p>
                        <input id="btnDetails" type="button" value="Detaljer" onclick="location.href='@Url.Action("AlchoholDetails", "Drink", new { drinkId = d.ID })'" />
                    }
                 </td>
            </tr>
        }
        </table>
        <hr />

        <h2>Hel Flasker</h2>
        <table style="margin-left:50px;">
        @foreach (Gui.MenucardServiceRef.HelFlask d in Model.helflasks)
        {
            <tr>
                <th>
                    <h3>@d.Name</h3>
                </th>
            </tr>
            <tr>
                <th width="270px" rowspan="3">
                    <a href="@Url.Action("HelflaskDetails", "Drink", new { drinkId = d.ID })"><img src="@Url.Content(d.Img)" alt="" height="200px" width="auto" /></a>
                </th>
                <td valign="top">
                    Procent: @d.Procent
                </td>
            </tr>
            <tr>
                <td valign="top">
                    Pris: @d.Price dkk. <br />
                    Antal tilbage; @sClient.getHelflaskStorageByHelflaskAndStorage(d.ID, Model.Customer.ID).Amount;
                </td>
            </tr>
            <tr>
                <td valign="bottom">
                    @if (AuthHelper.IsLoggedIn())
                    {
                        if (sClient.getHelflaskStorageByHelflaskAndStorage(d.ID, Model.Customer.ID) == null ||
                            sClient.getHelflaskStorageByHelflaskAndStorage(d.ID, Model.Customer.ID).Amount <= 0)
                        {
                            <p>UDSOLGT!</p>
                        }
                        else
                        {
                            using (Html.BeginForm("CreateHelflask", "Drink", FormMethod.Post))
                            {
                                <input type="hidden" name="drinkId" value="@d.ID" />
                                <input type="hidden" name="cusID" value="@Model.Customer.ID" />
                                <input type="text" id="txtAmount" name="amount" value="" style="width:30px;" />
                                <input type="hidden" name="UserName" value="@AuthHelper.CurrentUser.Username" />
                                <input type="submit" id="sumbitText" value="Tilføj" />
                                <input id="btnDetails" type="button" value="Detaljer" onclick="location.href='@Url.Action("HelflaskDetails", "Drink", new { drinkId = d.ID })'" />
                            }
                        }
                    }
                    else
                    {
                        <p> Du skal være logget ind før du kan købe</p>
                        <input id = "btnDetails" type = "button" value = "Detaljer" onclick = "location.href='@Url.Action("HelflaskDetails", "Drink", new { drinkId = d.ID })'" />
                    }
                </td>
            </tr>
        }
        </table>
    </dl>
</div>
<p>
    @Html.ActionLink("Tilbage til listen", "Findbar", "Home")
</p>

Projekt Mappe/Website/Gui/Views/Customer/SearchMenucard.cshtml
@model Gui.MenucardServiceRef.MenuCard
@using Gui.CustomerServiceRef
@using Gui.DrinkServiceRef
@using Gui.Helpers

<h2>@Model.Customer.CusName</h2>

<div style="color:white;">
    <h4>MenuCard</h4>
    <hr />
    @using (Html.BeginForm("SearchMenucard", "Customer", FormMethod.Post))
    {
        <input type="text" name="text" value="" />
        <input type="hidden" name="id" value="@Model.Customer.ID" />
        <input type="submit" id="sumbitText" value="Søg" />
    }
    <dl class="dl-horizontal">
        <h2>Drinks</h2>
        <table style="margin-left:50px;">
            @foreach (Gui.MenucardServiceRef.Drink d in Model.Drinks)
            {
                <tr>
                    <th>
                        <h3>@d.Name</h3>
                    </th>
                </tr>
                <tr>
                    <th width="270px" rowspan="3">
                        <a href="@Url.Action("Details", "Drink", new { drinkId = d.ID })"><img src="@Url.Content(d.Img)" alt="" height="200px" width="auto" /></a>
                    </th>
                    <td valign="top">
                        @d.Description
                    </td>
                </tr>
                <tr>
                    <td valign="top">
                        Pris: @d.Price dkk.
                    </td>
                </tr>
                <tr>
                    <td valign="bottom">
                        @if (AuthHelper.IsLoggedIn())
                        {<input id="Button1" type="submit" value="Add To Cart" onclick="location.href='@Url.Action("Create", "Drink", new { drinkId = d.ID, cusID = Model.Customer.ID, userName = AuthHelper.CurrentUser.Username })'" />}
                        else
                        {<p>Du skal være logget ind før du kan købe</p>}
                        @*<input id="Button1" type="submit" value="Add To Cart" onclick="location.href='@Url.Action("Create", "Drink", new { drinkId = d.ID, cusID = Model.Customer.ID })'" />*@
                        <input id="btnDetails" type="button" value="Details" onclick="location.href='@Url.Action("Details", "Drink", new { drinkId = d.ID })'" />
                    </td>
                </tr>
            }
        </table>
        <hr />

        <h2>Alkohol</h2>
        <table style="margin-left: 50px;">
            @foreach (Gui.MenucardServiceRef.Alchohol d in Model.alchohols)
            {
                <tr>
                    <th>
                        <h3>@d.Name</h3>
                    </th>
                </tr>
                <tr>
                    <th width="270px" rowspan="3">
                        <a href="@Url.Action("AlchoholDetails", "Drink", new { drinkId = d.ID })"><img src="@Url.Content(d.Img)" alt="" height="200px" width="auto" /></a>
                    </th>
                    <td valign="top">
                        Procent: @d.Procent
                    </td>
                </tr>
                <tr>
                    <td valign="top">
                        Pris: @d.Price dkk.
                    </td>
                </tr>
                <tr>
                    <td valign="bottom">
                        @if (AuthHelper.IsLoggedIn())
                        {<input id="Button1" type="submit" value="Add To Cart" onclick="location.href='@Url.Action("CreateAlchohol", "Drink", new { drinkId = d.ID, cusID = Model.Customer.ID, userName = AuthHelper.CurrentUser.Username })'" />}
                        else
                        {<p>Du skal være logget ind før du kan købe</p>}
                        <input id="btnDetails" type="button" value="Details" onclick="location.href='@Url.Action("AlchoholDetails", "Drink", new { drinkId = d.ID })'" />
                    </td>
                </tr>
            }
        </table>
        <hr />

        <h2>Hel Flasker</h2>
        <table style="margin-left:50px;">
            @foreach (Gui.MenucardServiceRef.HelFlask d in Model.helflasks)
            {
                <tr>
                    <th>
                        <h3>@d.Name</h3>
                    </th>
                </tr>
                <tr>
                    <th width="270px" rowspan="3">
                        <a href="@Url.Action("HelflaskDetails", "Drink", new { drinkId = d.ID })"><img src="@Url.Content(d.Img)" alt="" height="200px" width="auto" /></a>
                    </th>
                    <td valign="top">
                        Procent: @d.Procent
                    </td>
                </tr>
                <tr>
                    <td valign="top">
                        Pris: @d.Price dkk.
                    </td>
                </tr>
                <tr>
                    <td valign="bottom">
                        @if (AuthHelper.IsLoggedIn())
                        {<input id="Button1" type="submit" value="Add To Cart" onclick="location.href='@Url.Action("CreateHelflask", "Drink", new { drinkId = d.ID, cusID = Model.Customer.ID, userName = AuthHelper.CurrentUser.Username })'" />}
                        else
                        {<p>Du skal være logget ind før du kan købe</p>}
                        <input id="btnDetails" type="button" value="Details" onclick="location.href='@Url.Action("HelflaskDetails", "Drink", new { drinkId = d.ID })'" />
                    </td>
                </tr>
            }
        </table>
    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>